const awards = [
  { title: '대한의용생체공학회 2025년 춘계학술대회 우수논문 대상', recipient: '박영현', organization: '대한의용생체공학회', year: '2025' },
  { title: '대한디지털헬스학회 우수상', recipient: '강현영', organization: '대한디지털헬스학회', year: '2024' },
  { title: '대한디지털헬스학회 최우수상', recipient: '이세나', organization: '대한디지털헬스학회', year: '2024' },
  { title: '대한의용생체공학회 우수포스터논문상 우수상', recipient: '이세나', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 우수포스터논문상 최우수상', recipient: '강현영', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 추계학술대회 우수논문상', recipient: '정진교', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 추계학술대회 우수논문상', recipient: '박영현', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 추계학술대회 우수논문상', recipient: '류지승', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의학영상정보학회 학술대회  장려포스터상', recipient: '한중훈', organization: '대한의학영상정보학회', year: '2024' },
  { title: '대한의학영상정보학회 학술대회 장려포스터상', recipient: '정진교', organization: '대한의학영상정보학회', year: '2024' },
  { title: '대한의용생체공학회 2024년 춘계학술대회 우수포스터 논문상', recipient: '한중훈', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 2024년 춘계학술대회 우수논문상', recipient: '정진교', organization: '대한의용생체공학회', year: '2024' },
  { title: '대한의용생체공학회 2023년 추계학술대회 우수논문상', recipient: '김근혜', organization: '대한의용생체공학회', year: '2023' },
  { title: '대한의용생체공학회 2023년 추계학술대회 우수 포스터 논문상', recipient: '강현영', organization: '대한의용생체공학회', year: '2023' },
  { title: '대한디지털헬스학회 우수상', recipient: '이세나', organization: '대한디지털헬스학회', year: '2023' },
  { title: '대한의용생체공학회 2023년 춘계학술대회 우수포스터상', recipient: '서경덕', organization: '대한의용생체공학회', year: '2023' },
  { title: '대한의용생체공학회  2023년 춘계학술대회 우수논문상', recipient: '이세나', organization: '대한의용생체공학회', year: '2023' },
  { title: '보건의료빅데이터 디지털헬스테어사업아이디어 경진대회 최우수상', recipient: '강현영', organization: '건강보험심사평가원, 강원테크노파크', year: '2022' },
  { title: '창업아이디어공모전 최우수상', recipient: '강현영', organization: '연세대학교 의공학과', year: '2022' },
  { title: '대한의용생체공학회 2022년 추계학술대회', recipient: '이세나', organization: '한중훈, 추유성, 진용규, 양세정, 대한의용생체공학회', year: '2022' },
  { title: '라이프로그 빅데이터 활용 및 제안 해커톤', recipient: '류지승', organization: '장승현, 이예린, 서경덕, 강현영, 원주연세의료원 라이프로그빅데이터 플랫폼, 건강보험빅데이터진료지원플랫폼', year: '2022' },
  { title: '라이프로그 빅데이터 활용 및 제안 해커톤', recipient: '강승영', organization: '이세나, 한중훈, 추유성, 원주연세의료원 라이프로그빅데이터 플랫폼, 건강보험빅데이터진료지원플랫폼', year: '2022' },
  { title: '보건의료 빅데이터 디지털 헬스케어 사업 아이디어 경진대회', recipient: '강승영', organization: '건강보험심사평가원, 강원테크노파크', year: '2022' },
  { title: '보건의료 빅데이터 디지털 헬스케어 사업 아이디어 경진대회', recipient: '한중훈', organization: '건강보험심사평가원, 강원테크노파크', year: '2022' },
  { title: '보건의료 빅데이터 디지털 헬스케어 사업 아이디어 경진대회', recipient: '이세나', organization: '건강보험심사평가원, 강원테크노파크', year: '2022' },
];
