const photos = [
  { title: '2025년도 제66회 대한의용생체공학회 추계 학술대회', image: 'assets/gallery/photo_001.jpg' },
  { title: 'MICCAI 2025', image: 'assets/gallery/photo_002.jpg' },
  { title: '2025년도 대한의학영상정보학회 제 39차 학술대회', image: 'assets/gallery/photo_003.jpg' },
  { title: '2025년도 5월 27일 연구실 제천 워크샵', image: 'assets/gallery/photo_004.jpg' },
  { title: '2025년도 제65회 대한의용생체공학회 춘계 학술대회', image: 'assets/gallery/photo_005.jpg' },
  { title: '2024 연구실 송년회', image: 'assets/gallery/photo_006.jpg' },
  { title: '2024 해외 학회 IEEE BIBM', image: 'assets/gallery/photo_007.jpg' },
  { title: '2024 추계 대한디지털헬스학회', image: 'assets/gallery/photo_008.jpg' },
  { title: '2024 추계 의공학회', image: 'assets/gallery/photo_009.jpg' },
  { title: '2024년 여름 회식', image: 'assets/gallery/photo_010.jpg' },
  { title: '2024 대한의학영상정보학회', image: 'assets/gallery/photo_011.jpg' },
  { title: '2024 스승의날', image: 'assets/gallery/photo_012.jpg' },
  { title: '2024 춘계 대한의용생체공학회 참여', image: 'assets/gallery/photo_013.jpg' },
  { title: '2024년 4월 점심식사', image: 'assets/gallery/photo_014.jpg' },
  { title: '2024년 1월 점심식사', image: 'assets/gallery/photo_015.jpg' },
  { title: 'LAIBI 송년회 & 신년회', image: 'assets/gallery/photo_016.jpg' },
  { title: '2023 추계 의공학회 방문', image: 'assets/gallery/photo_017.png' },
  { title: '2023년 대한의료영상정보학회', image: 'assets/gallery/photo_018.jpg' },
  { title: '2023년 춘계 의공학회', image: 'assets/gallery/photo_019.jpg' },
  { title: '2023 4월 점심식사', image: 'assets/gallery/photo_020.jpg' },
  { title: '미국 의료영상기기 회사 방문', image: 'assets/gallery/photo_021.jpg' },
  { title: '2023  SPIE PHOTONICS WEST 국제 학회', image: 'assets/gallery/photo_022.jpg' },
  { title: '2023 LAIBI 신년회', image: 'assets/gallery/photo_023.jpg' },
  { title: '2022  대한 의용 생체 공학회', image: 'assets/gallery/photo_024.jpg' },
  { title: '2022 스승의날', image: 'assets/gallery/photo_025.jpg' },
  { title: 'ICEIC 2022', image: 'assets/gallery/photo_026.jpg' },
  { title: '2021 하계 전자공학회', image: 'assets/gallery/photo_027.jpg' },
  { title: '2021 스승의날', image: 'assets/gallery/photo_028.jpg' },
  { title: '2020 하계 전자공학회', image: 'assets/gallery/photo_029.jpg' },
  { title: '2020 9월 회식', image: 'assets/gallery/photo_030.jpg' },
  { title: '오스템 임플란트 초청 방문', image: 'assets/gallery/photo_031.jpg' },
];
