// news_data.js — 실제 논문·수상·연구실 소식
const newsData = [
  { date: '2025.06', text: 'Paper published in <strong>Frontiers in Pain Research</strong> (IF=2.7) — "Classifying office workers with cervicogenic headache using posture-based deep learning models"' },
  { date: '2025.06', text: 'Paper published in <strong>Biomedical Engineering Letters</strong> (IF=2.8) — "Vision-language foundation models for medical imaging: a review"' },
  { date: '2025.05', text: '대한의용생체공학회 2025 춘계학술대회 <strong>우수논문 대상</strong> 수상 — 박영현' },
  { date: '2025.05', text: 'Kosomebe 2025에 9편의 논문 발표 (의료 파운데이션 모델, 안진 검출, 복부 CT 분석 등)' },
  { date: '2025.04', text: 'Paper published in <strong>Scientific Reports</strong> (IF=3.9) — "A deep learning approach for blood glucose monitoring in glycogen storage disease"' },
  { date: '2025.04', text: 'Paper published in <strong>Journal of Biomedical Engineering Research</strong> — "A Framework for Facial Vitiligo Area Measurement Based on 3D Face Reconstruction"' },
  { date: '2025.01', text: 'Paper published in <strong>Dermatology Therapy</strong> (IF=3.7) — "Deep Learning Algorithms for Assessment of Post-Thyroidectomy Scar Subtype"' },
  { date: '2025.01', text: 'Paper published in <strong>IEEE JBHI</strong> (IF=6.7) — "Class-Agnostic Feature-Learning-Based Deep-Learning Model for Robust Melanoma Prediction"' },
  { date: '2024.12', text: 'IEEE BIBM 2024에 8편의 논문 발표 (췌장 이상 탐지, 갑상선 수술 흉터 예측, 창상 조직 분할 등)' },
  { date: '2024.12', text: 'RSNA 2024 발표 — "Latent Diffusion Model Approach for Improved Diagnosis of Pancreatic Anomaly Detection"' },
  { date: '2024.11', text: '대한디지털헬스학회 <strong>최우수상</strong> 수상 — 이세나' },
  { date: '2024.11', text: '대한디지털헬스학회 <strong>우수상</strong> 수상 — 강현영' },
  { date: '2024.11', text: '대한의용생체공학회 추계학술대회 <strong>우수논문상</strong> 수상 — 정진교, 박영현, 류지승' },
  { date: '2024.11', text: '대한의용생체공학회 <strong>우수포스터논문상 최우수상</strong> 수상 — 강현영' },
  { date: '2024.11', text: '대한의용생체공학회 <strong>우수포스터논문상 우수상</strong> 수상 — 이세나' },
  { date: '2024.10', text: 'Paper published in <strong>Journal of Biomedical Engineering Research</strong> — "내시경 수술을 위한 딥러닝 시스템 통합형 영상 강화 및 연기 제거"' },
  { date: '2024.07', text: '대한의학영상정보학회 학술대회 장려포스터상 수상 — 한중훈, 정진교' },
  { date: '2024.05', text: 'Paper published in <strong>Biomedical Signal Processing and Control</strong> (IF=4.9) — "Chromosome analysis method based on deep learning"' },
  { date: '2024.05', text: '대한의용생체공학회 2024 춘계학술대회 <strong>우수포스터 논문상</strong> 수상 — 한중훈' },
  { date: '2024.05', text: '대한의용생체공학회 2024 춘계학술대회 <strong>우수논문상</strong> 수상 — 정진교' },
  { date: '2024.03', text: 'Paper published in <strong>Computers in Biology and Medicine</strong> (IF=7.0) — "Cellular subpopulations identified using an ensemble average of multiple dielectrophoresis measurements"' },
  { date: '2024.01', text: 'SPIE 2024에 6편의 논문 발표 (멜라노마 깊이 예측, 안진 검출, ECG 부정맥 분류 등)' },
  { date: '2023.12', text: 'Paper published in <strong>Scientific Reports</strong> (IF=4.997) — "Deep learning framework for automated goblet cell density analysis"' },
  { date: '2023.11', text: '대한의용생체공학회 2023 추계학술대회 <strong>우수논문상</strong> 수상 — 김근혜' },
  { date: '2023.11', text: '대한의용생체공학회 2023 추계학술대회 <strong>우수포스터논문상</strong> 수상 — 강현영' },
  { date: '2023.11', text: 'Paper published in <strong>Materials Horizons</strong> (IF=13.3) — "Full automation of point defect detection in transition metal dichalcogenides"' },
  { date: '2023.07', text: 'Paper published in <strong>Scientific Reports</strong> (IF=4.997) — "A nystagmus extraction system using artificial intelligence"' },
  { date: '2023.06', text: 'Paper published in <strong>Biomedical Engineering Letters</strong> (IF=4.6) — "Ventricle tracking in TEE images during CPR using deep learning"' },
  { date: '2023.06', text: 'Paper published in <strong>PLOS ONE</strong> — "CoAt-Mixer: Self-attention deep learning framework for left ventricular hypertrophy using ECG"' },
  { date: '2023.05', text: '대한의용생체공학회 2023 춘계학술대회 <strong>우수포스터상</strong> 수상 — 서경덕' },
  { date: '2023.05', text: '대한의용생체공학회 2023 춘계학술대회 <strong>우수논문상</strong> 수상 — 이세나' },
];
