// projects_data.js
const projects = [

  // ── 내과 Internal Medicine ──────────────────────────────────
  {
    title: 'ECG-Based Left Ventricular Hypertrophy Detection',
    category: 'Internal Medicine',
    status: 'completed',
    desc: 'Deep learning model (CoAt-Mixer & ResNet-CBAM) for diagnosing left ventricular hypertrophy (LVH) using large-scale ECG data. Published in PLOS One 2023 (IF: 3.7, JCR Q1).',
    slides: ['assets/projects/Internal Medicine/slide_09.jpg', 'assets/projects/Internal Medicine/slide_10.jpg', 'assets/projects/Internal Medicine/slide_11.jpg'],
  },
  {
    title: 'ECG-Based Left Ventricular Diastolic Dysfunction Detection',
    category: 'Internal Medicine',
    status: 'ongoing',
    desc: 'Ensemble deep learning model (CoAt-Mixer & ResNet-CBAM) for diagnosing left ventricular diastolic dysfunction (LVDD) from ECG signals. Paper in preparation.',
    slides: ['assets/projects/Internal Medicine/slide_12.jpg', 'assets/projects/Internal Medicine/slide_13.jpg', 'assets/projects/Internal Medicine/slide_14.jpg'],
  },
  {
    title: 'AI-Based Classification of Gastrointestinal Tumors',
    category: 'Internal Medicine',
    status: 'ongoing',
    desc: 'CLIP-based multi-modal model integrating endoscopic images and clinical text to predict invasion depth and curative resection rates of gastrointestinal tumors. Paper in progress.',
    slides: ['assets/projects/Internal Medicine/slide_15.jpg', 'assets/projects/Internal Medicine/slide_16.jpg', 'assets/projects/Internal Medicine/slide_17.jpg'],
  },
  {
    title: 'Endoscopic Surgical Visibility Enhancement',
    category: 'Internal Medicine',
    status: 'completed',
    desc: 'Generative AI system for simultaneous smoke removal and image enhancement in endoscopic surgery. Domestic patent filed (10-2024-0178977), technology transferred, and awarded Best Paper at KOSOMBE 2024.',
    slides: ['assets/projects/Internal Medicine/slide_55.jpg', 'assets/projects/Internal Medicine/slide_56.jpg', 'assets/projects/Internal Medicine/slide_57.jpg'],
  },

  // ── 영상의학과 Radiology ────────────────────────────────────
  {
    title: 'Multi-modal CT + Clinical Data for Hepatic Portal Hypertension',
    category: 'Radiology',
    status: 'ongoing',
    desc: 'Multi-modal deep learning model combining 3D abdominal CT (Swin-Transformer) and clinical text (BLIP) for non-invasive prediction of clinically significant portal hypertension (HVPG ≥ 10 mmHg). Validated at SoonChunHyang University Bucheon Hospital. Paper in progress.',
    slides: ['assets/projects/Radiology/slide_18.jpg', 'assets/projects/Radiology/slide_19.jpg', 'assets/projects/Radiology/slide_20.jpg', 'assets/projects/Radiology/slide_21.jpg', 'assets/projects/Radiology/slide_22.jpg'],
  },
  {
    title: 'Generative AI-Based Pancreatic Anomaly Detection in Abdominal CT',
    category: 'Radiology',
    status: 'ongoing',
    desc: 'Unsupervised anomaly detection for pancreatic diseases in abdominal CT using generative models trained only on normal data. Anomaly maps generated by comparing generated normal images with abnormal inputs. Paper in progress.',
    slides: ['assets/projects/Radiology/slide_24.jpg', 'assets/projects/Radiology/slide_25.jpg', 'assets/projects/Radiology/slide_26.jpg'],
  },

  // ── 소아과 Pediatrics ────────────────────────────────────────
  {
    title: 'Personalized Blood Glucose Management for Glycogen Storage Disease',
    category: 'Pediatrics',
    status: 'ongoing',
    desc: 'Personalized deep learning models (LTSF N-Linear, TS Mixer) for blood glucose forecasting and hypoglycemia classification in glycogen storage disease (GSD) patients using CGM data. Published in Scientific Reports 2025 (IF: 3.8, JCR Q1).',
    slides: ['assets/projects/Pediatrics/slide_28.jpg', 'assets/projects/Pediatrics/slide_30.jpg', 'assets/projects/Pediatrics/slide_31.jpg'],
  },

  // ── 피부과 Dermatology ──────────────────────────────────────
  {
    title: 'Acral Lentiginous Melanoma (ALM) Detection',
    category: 'Dermatology',
    status: 'completed',
    desc: 'ALMNet deep learning model for augmented decision-making in acral lentiginous melanoma detection from dermoscopic images. Published in JEADV 2020 (IF: 9.228, JCR Top 5.3%, Rank 5/94 in Dermatology).',
    slides: ['assets/projects/Dermatology/slide_36.jpg', 'assets/projects/Dermatology/slide_37.jpg', 'assets/projects/Dermatology/slide_38.jpg'],
  },
  {
    title: 'Breslow Thickness Prediction for Acral Melanoma',
    category: 'Dermatology',
    status: 'completed',
    desc: 'CNN-based non-invasive prediction model for Breslow thickness of acral lentiginous melanoma from dermoscopic images. Published in Journal of Investigative Dermatology 2022 (IF: 7.59, JCR Top 6.4%, Rank 6/94 in Dermatology).',
    slides: ['assets/projects/Dermatology/slide_39.jpg', 'assets/projects/Dermatology/slide_40.jpg'],
  },
  {
    title: 'Robust Melanoma Prediction via Consistent Deep Learning',
    category: 'Dermatology',
    status: 'ongoing',
    desc: 'Deep learning method for consistent and robust melanoma prediction across slight image variations of the same lesion. Accepted for publication in IEEE Journal of Biomedical and Health Informatics (JBHI; IF: 6.7, JCR Top 5.7%).',
    slides: ['assets/projects/Dermatology/slide_41.jpg', 'assets/projects/Dermatology/slide_42.jpg'],
  },
  {
    title: 'AI-Based 3D Facial Vitiligo Area Measurement',
    category: 'Dermatology',
    status: 'ongoing',
    desc: '3D face reconstruction and UV mapping framework for automated quantification of facial vitiligo area. Parts published in Biomedical Engineering 2025; preparing for submission to JAMA Dermatology.',
    slides: ['assets/projects/Dermatology/slide_43.jpg', 'assets/projects/Dermatology/slide_44.jpg', 'assets/projects/Dermatology/slide_45.jpg', 'assets/projects/Dermatology/slide_46.jpg'],
  },
  {
    title: 'AI-Based 3D Alopecia Areata (SALT Score) Assessment',
    category: 'Dermatology',
    status: 'ongoing',
    desc: '3D head reconstruction and UV texture mapping for automated SALT score measurement in alopecia areata. CNN-based segmentation of hair loss area on reconstructed 3D mesh. Preparing for submission to JAMA Dermatology.',
    slides: ['assets/projects/Dermatology/slide_47.jpg', 'assets/projects/Dermatology/slide_48.jpg', 'assets/projects/Dermatology/slide_49.jpg'],
  },

  // ── 성형외과 Plastic Surgery ────────────────────────────────
  {
    title: 'Multi-Task Learning for Wound Detection and Tissue Segmentation',
    category: 'Plastic Surgery',
    status: 'ongoing',
    desc: 'WISE-MTL framework with GradNorm for simultaneous wound boundary detection and tissue type segmentation (granulation, slough, necrosis, epithelial). Outperforms single-task learning across all tissue types. Submitted to PLOS One (IF: 2.9).',
    slides: ['assets/projects/Plastic Surgery/slide_51.jpg', 'assets/projects/Plastic Surgery/slide_52.jpg', 'assets/projects/Plastic Surgery/slide_53.jpg'],
  },

  // ── 병리과 Pathology ─────────────────────────────────────────
  {
    title: 'Frozen Section to FFPE Style Translation for Skin Pathology',
    category: 'Pathology',
    status: 'ongoing',
    desc: 'Generative AI model (CUT-based) for translating frozen section (FS) histology slides to formalin-fixed paraffin-embedded (FFPE) style, targeting skin cancers (melanoma, EMPD, Bowen\'s disease). Enables intraoperative diagnosis quality comparable to the gold standard.',
    slides: ['assets/projects/Pathology/slide_60.jpg', 'assets/projects/Pathology/slide_61.jpg'],
  },

  // ── 이비인후과 Otorhinolaryngology ───────────────────────────
  {
    title: 'AI-Based BPPV Nystagmus Detection and Diagnosis',
    category: 'Otorhinolaryngology',
    status: 'completed',
    desc: 'Automated eye tracking and nystagmus detection from VNG (video-nystagmography) data for AI-assisted diagnosis of benign paroxysmal positional vertigo (BPPV). Published in Scientific Reports 2023 (IF: 4.6, JCR Q1). Preparing for submission to JAMA Otolaryngology.',
    slides: ['assets/projects/Otorhinolaryngology/slide_64.jpg', 'assets/projects/Otorhinolaryngology/slide_65.jpg'],
  },

  // ── 갑상선 내분비외과 Thyroid and Endocrine Surgery ──────────
  {
    title: 'Deep Learning for Thyroid Fine-Needle Aspiration Cytopathology',
    category: 'Thyroid and Endocrine Surgery',
    status: 'ongoing',
    desc: 'Deep learning model for automated classification of thyroid nodule cytology slides obtained by fine-needle aspiration (FNA) according to the Bethesda System (Categories I–VI). Research in progress.',
    slides: ['assets/projects/Thyroid and Endocrine Surgery/slide_68.jpg', 'assets/projects/Thyroid and Endocrine Surgery/slide_69.jpg'],
  },

  // ── 융합의과학부 Convergence Medicine ───────────────────────
  {
    title: 'AI-Based Mitochondrial TEM Image Analysis for Sarcopenia',
    category: 'Convergence Medicine',
    status: 'ongoing',
    desc: 'Automated analysis of mitochondrial ultrastructure in transmission electron microscopy (TEM) images using MICRO-SAM segmentation and ResNet-50 feature extraction for t-SNE clustering. Targets sarcopenia-related mitochondrial dysfunction assessment.',
    slides: ['assets/projects/Convergence Medicine/slide_72.jpg'],
  },

  // ── 교정과 Orthodontics ─────────────────────────────────────
  {
    title: 'AI-Based 3D Tooth Segmentation for Orthodontic Analysis',
    category: 'Orthodontics',
    status: 'ongoing',
    desc: '2D rendering-based detection and binary segmentation of individual teeth from 3D intraoral scan meshes. Handles missing and malaligned teeth robustly by simplifying the learning structure through per-tooth patch segmentation.',
    slides: ['assets/projects/Orthodontics/slide_75.jpg', 'assets/projects/Orthodontics/slide_76.jpg'],
  },
];
